version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: develop
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: portfolio-app
    working_dir: /usr/src/app/backend
    stdin_open: true
    tty: true
    command: bash -c "
      rm -rf tmp/pids/server.pid &&
      bundle exec rails s -b 0.0.0.0"
    volumes:
      - ./backend:/usr/src/app/backend
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      TZ: Asia/Tokyo
  node:
    image: node:21-alpine
    container_name: portfolio-node
    working_dir: /usr/src/app
    command: yarn start
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "8000:8000"
volumes:
  db:
    driver: local
  bundle:
    driver: local