inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/*'
    - 'config/environments/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/SymbolArray:
  EnforcedStyle: brackets

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
