AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'config/*'
    - 'config/environments/*'
    - 'db/migrate/**/*'
    - 'db/schema.rb'
    - 'vendor/**/*'
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'

Style/Documentation:
  Exclude:
    - 'app/mailers/application_mailer.rb'
    - 'app/models/application_record.rb'

Style/SymbolArray:
  EnforcedStyle: brackets

RSpecRails/InferredSpecType:
  Enabled: false

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
  - rubocop-rspec_rails
